INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','fuck');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','fck');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','shit');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','sh!t');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','sh1t');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','s-h-1-t');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','asshole');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','ass hole');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','bitch');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','bitch');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','jerk');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','dumbass');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','dumb');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','damn');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','stfu');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','suck');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','dick');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','whore');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','go to hell');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','son of a bitch');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','motherfucker');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','motherfucking');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','piss off');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('Verbal_Abuse','pissoff');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('disability harassment','bastard');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('disability harassment','retard');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('racial harassment','chingchong');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('racial harassment','ching');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('racial harassment','negro');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','anal');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','gangbang');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','gang bang');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','rape');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','raping');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','rapist');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','orgasms');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','orgasmic');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','pussy');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','penail');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','threesome');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','fist fuck');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','fistfuckings');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','fist——fuck');
INSERT INTO `bad_word_pattern` (`name`, `pattern`) VALUES ('sexual_related','fisting');
