INSERT INTO `images` (`name`, `data`) VALUES ('test', 'ὃ⍜ὅ');
INSERT INTO `images` (`name`, `data`) VALUES ('test', 'චᆽච');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(๑•̀ㅂ•́)و✧');
INSERT INTO `images` (`name`, `data`) VALUES ('test', 'ฅ•ω•ฅ');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '<(￣︶￣)>');
INSERT INTO `images` (`name`, `data`) VALUES ('test', 'ヾ(≧▽≦*)o');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '⊙▽⊙');
INSERT INTO `images` (`name`, `data`) VALUES ('test', 'φ(≧ω≦*)♪');
INSERT INTO `images` (`name`, `data`) VALUES ('test', 'o(*￣︶￣*)o');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(/≧▽≦)/');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(*/ω＼*)');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '◔ ‸◔?');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '╮(๑•́ ₃•̀๑)╭');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(ง •̀_•́)ง (*•̀ㅂ•́)و');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '꒰๑´•.̫ • `๑꒱');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(..•˘_˘•..)');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '(๑•́ ₃•̀๑)');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '🙄');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '🥰');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '😭');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '😘');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '😅');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '🤫');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '😂');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '😷');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👍🏻');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👍');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👎🏻');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👌');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '🙏');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👊');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👹');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👅');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '💩');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '👻');
INSERT INTO `images` (`name`, `data`) VALUES ('test', '🙈');
